djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from forum import urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(urls)),
]

forum/urls.py
from django.urls import path
from django.contrib.auth import views as authviews
from . import views

app_name = 'forum'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', authviews.login, {'template_name': 'forum/login.html'}, name='login'),
    path('logout/', authviews.logout, {'template_name': 'forum/logout.html'}, name='logout'),
    path('addthread/', views.add_thread, name='add_thread'),
    path('profile/<str:username>/', views.see_profile, name='see_profile'),
    path('profile/<str:username>/userdelete', views.user_delete, name='user_delete'),
    path('profile/<str:username>/profileupdate/', views.profile_update, name='profile_update'),
    path('profile/<str:username>/passwdchange/', views.password_change, name='password_change'),
    path('<str:category>/', views.threadlist, name='threadlist'),
    path('<str:category>/<int:threadID>/', views.thread_details, name='thread_details'),
    path('<str:category>/<int:threadID>/answer', views.answer, name='answer'),
    path('<str:category>/<int:threadID>/deletethread', views.thread_delete, name='thread_delete'),
    path('<str:category>/<int:threadID>/<int:postID>/deletepost', views.post_delete, name='delete_post')
]

forum/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Thread(models.Model):
    category_name = models.CharField(max_length=100)
    title = models.CharField(max_length=300)
    description = models.TextField()
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    creation_date = models.DateTimeField(default=timezone.now)
    last_activity_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class Post(models.Model):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    text = models.TextField()
    posting_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "In \"" + str(self.thread.title) + "\" by " + str(self.author) + " - " + str(self.posting_date)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    text = models.TextField()
    posting_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "In \"" + str(self.post.thread.title) + "\" comment by " + str(self.author) + " - " + str(self.posting_date)

forum/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Thread, Post


class MySignUpForm(UserCreationForm):
    # imie_i_nazwisko = forms.CharField(max_length=100, required=False, help_text='Nie wymagane')
    first_name = forms.CharField(label='Imię', max_length=100, required=False, help_text='Nie wymagane')
    last_name = forms.CharField(label='Nazwisko', max_length=100, required=False, help_text='Nie wymagane')
    email = forms.EmailField(max_length=150)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

    def __init__(self, *args, **kwargs):
        super(MySignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].help_text = 'Maksymalnie 150 znaków. Jedynie litery, cyfry i @/./+/-/_.'
        self.fields['password1'].help_text = 'Twoje hasło musi zawierać co najmniej 8 znaków. '


class ThreadForm(forms.ModelForm):

    class Meta:
        model = Thread
        fields = {'category_name', 'title', 'description'}

    def __init__(self, *args, **kwargs):
        super(ThreadForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs['style'] = 'width:800px; height:150px'
        self.fields['title'].widget.attrs['style'] = 'width:600px; height:25px'
        self.fields['category_name'].widget.attrs['style'] = 'width:300px; height:25px'
        self.fields.keyOrder = ['title', 'category_name', 'description']
        self.fields['category_name'].label = 'Kategoria'
        self.fields['title'].label = 'Tytuł'
        self.fields['description'].label = 'Opis'


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = {'text'}

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['text'].label = 'Komentarz'
        self.fields['text'].widget.attrs['cols'] = 100
        self.fields['text'].widget.attrs['rows'] = 15


class ProfileUpdateForm(forms.ModelForm):
    email = forms.EmailField(required=False, max_length=150)
    # imie_i_nazwisko = forms.CharField(required=False)
    first_name = forms.CharField(label='Imię', max_length=100, required=False, help_text='Nie wymagane')
    last_name = forms.CharField(label='Nazwisko', max_length=100, required=False, help_text='Nie wymagane')

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name')

forum/views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from django.contrib.auth import login, authenticate
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.utils import timezone
from .forms import *


def index(request):
    threadlist = Thread.objects.all()
    categories = []
    for thread in threadlist:
        if thread.category_name not in categories:
            categories.append(thread.category_name)
    cat1 = []
    cat2 = []
    for i in range(len(categories)):
        if i % 2 == 0:
            cat1.append(categories[i])
        else:
            cat2.append(categories[i])
    if len(cat1) > len(cat2):
        cat2.append("")
    context = {'categories': zip(cat1, cat2)}
    return render(request, 'forum/index.html', context)


def signup(request):
    if request.method == 'POST':
        form = MySignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('forum:index')
    else:
        form = MySignUpForm()
    return render(request, 'forum/signup.html', {'form': form})


def add_thread(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = ThreadForm(request.POST)
            if form.is_valid():
                notsaved = form.save(commit=False)
                notsaved.author = request.user
                notsaved.save()
                return redirect('forum:thread_details', category=notsaved.category_name, threadID=notsaved.pk)
        else:
            form = ThreadForm()
        return render(request, 'forum/add_thread.html', {'form': form})
    else:
        return redirect('forum:login')


def threadlist(request, category):
    threads = get_list_or_404(Thread, category_name=category)
    context = {'threads': threads, 'category': category}
    return render(request, 'forum/threadlist.html', context)


def thread_details(request, category, threadID):
    thread = get_object_or_404(Thread, pk=threadID)
    context = {'thread': thread, 'category': category}
    return render(request, 'forum/thread_details.html', context)


def see_profile(request, username):
    user = get_object_or_404(User, username=username)
    if request.user.is_authenticated:
        if request.user == user:
            context = {'user': user}
            return render(request, 'forum/see_profile.html', context)
    return redirect('forum:login')


def answer(request, category, threadID):
    thread = get_object_or_404(Thread, pk=threadID)
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PostForm(request.POST)
            if form.is_valid():
                notsaved = form.save(commit=False)
                thread.last_activity_date = timezone.now()
                thread.save()
                notsaved.author = request.user
                notsaved.thread = thread
                notsaved.save()
                context = {'thread': thread, 'category': category, 'form': form}
                # return render(request, 'forum/thread_details.html', context)
                return redirect('forum:thread_details', threadID=threadID, category=category)
        else:
            form = PostForm()
        context = {'thread': thread, 'category': category, 'form': form, 'message': 'Add answer'}
        return render(request, 'forum/thread_details.html', context)
    else:
        return redirect('forum:login')


def profile_update(request, username):
    user = get_object_or_404(User, username=username)
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = ProfileUpdateForm(request.POST)
            if form.is_valid():
                if form.cleaned_data['first_name']:
                    user.first_name = form.cleaned_data['first_name']
                if form.cleaned_data['last_name']:
                    user.last_name = form.cleaned_data['last_name']
                if form.cleaned_data.get('email'):
                    user.email = form.cleaned_data['email']
                user.save()
                return redirect('forum:see_profile', username=username)
        else:
            form = ProfileUpdateForm()
        return render(request, 'forum/profile_update.html', {'form': form})
    else:
        return redirect('forum:login')


def password_change(request, username):
    if request.user.is_authenticated:
        user = get_object_or_404(User, username=username)
        if request.user == user:
            if request.method == 'POST':
                form = PasswordChangeForm(request.user, request.POST)
                if form.is_valid():
                    user = form.save()
                    update_session_auth_hash(request, user)
                    return redirect('forum:see_profile', username=username)
            else:
                form = PasswordChangeForm(request.user)
            return render(request, 'forum/password_change.html', {'form': form})
    return redirect('forum:login')


def user_delete(request, username):
    if request.user.is_authenticated:
        user = get_object_or_404(User, username=username)
        if request.user == user:
            user.delete()
            return redirect('forum:index')
    return redirect('forum:login')


def thread_delete(request, category, threadID):
    if request.user.is_authenticated:
        thread = get_object_or_404(Thread, pk=threadID)
        if request.user == thread.author:
            thread.delete()
            return redirect('forum:index')
        else:
            return redirect('forum:thread_details', category=category, threadID=threadID)
    else:
        return redirect('forum:login')


def post_delete(request, category, threadID, postID):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=postID)
        if request.user == post.author:
            post.delete()
        return redirect('forum:thread_details', category=category, threadID=threadID)
    else:
        return redirect('forum:login')

forum/templates/forum/add_thread.html
{% extends 'forum/base.html' %}

{% block title %}
    <title>Dodawanie nowego wątku</title>
{%  endblock %}

{% block content %}
    <h2>Dodaj nowy wątek</h2>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <p>
                    {{ field.label_tag }}<br>
                    {{ field }}<br>
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </p>
            {% endfor %}
            <p>
                <button type="submit">Dodaj</button>
            </p>
        </form>
{% endblock %}

forum/templates/forum/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pl">
<head>
    <link rel="stylesheet" href="{% static 'css/styles/style.css' %}">
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
</head>

<body>
<div id="header-div">
    <ul>
      <li><a class="active" href="{% url 'forum:index' %}"><img src="../../static/css/home2.jpg" alt="Strona główna" height="14" width="17"></a></li>
      {% if user.is_authenticated %}
          <li style="float:right"><a href="{% url 'forum:logout' %}">Wyloguj</a></li>
          <li style="float:right"><a href="{% url 'forum:add_thread' %}">Dodaj wątek</a></li>
          <li style="float:right"><a href="{% url 'forum:see_profile' user.username %}">Profil</a></li>
      {% else %}
          <li style="float:right"><a href="{% url 'forum:login' %}">Zaloguj</a></li>
      {% endif %}
    </ul>
</div>
    {% block content %}
    {% endblock %}

</body>
</html>

forum/templates/forum/index.html
{% extends 'forum/base.html' %}
{% load staticfiles %}

{% block title %}
    <link rel="stylesheet" href="{% static 'css/styles/index.css' %}">
    <title>Forum</title>
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h2 align="middle">Witaj na forum {{ user.username }}!</h2>
    {% else %}
        <h2 align="middle">Nie jesteś zalogowany ☹</h2>
    {% endif %}
    <br>
    <table id="customers">
        <tr>
            <th colspan="2">Kategorie</th>
        </tr>
        {% for cat1, cat2 in categories %}
            <tr>
                <td><a href="{% url 'forum:threadlist' cat1 %}">{{ cat1 }}</a></td>
                {% if cat2 != "" %}
                    <td><a href="{% url 'forum:threadlist' cat2 %}">{{ cat2 }}</a></td>
                {% else %}
                    <td style="background-color: transparent; opacity: 0.0; border: none;">{{ cat2 }}</td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
{% endblock %}

forum/templates/forum/login.html
{% extends 'forum/base.html' %}
{% load staticfiles %}

{% block title %}
    <style>
        body {
            background: antiquewhite url("../../static/css/ksiazka.jpg") no-repeat center;
            background-size: 1280px;
            background-position: 300px 80px;
        }

        .position {
            margin: auto;
            width: 46%;
            padding: 100px;
        }

        h2 {
            color: darkslategrey;
        }
    </style>
    <title>Logowanie</title>
{% endblock %}

{% block content %}
    <div class="position">
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p style="word-spacing: 3.4cm; ">
            <button type="submit">Login</button>
            <input type="button" value="Rejestracja" onclick="window.location.href='{% url 'forum:signup' %}'">
            </p>
        </form>
    </div>
{% endblock %}

forum/templates/forum/logout.html
{% extends 'forum/base.html' %}
{% load staticfiles %}

{% block title %}
    <link rel="stylesheet" href="{% static 'css/styles/index.css' %}">
    <title>Wylogowano</title>
{% endblock %}

{% block content %}
    <h2 align="middle">Wylogowano</h2>
{% endblock %}

forum/templates/forum/password_change.html
{% extends 'forum/base.html' %}

{% block title %}
    <title>Zmiana hasła</title>
{% endblock %}

{% block content %}
    <form method="post">
    {% csrf_token %}
        {% for field in form %}
            <h4>{{ field.label_tag }}</h4><br>
            {{ field }}<br>
            {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
            {% endfor %}
        {% endfor %}
        <br><button type="submit">Zatwierdź</button>
    </form>
{% endblock %}

forum/templates/forum/profile_update.html
{% extends 'forum/base.html' %}

{% block title %}
    <title>Edycja profilu</title>
{% endblock %}

{% block content %}
    <h2>Edycja profilu</h2>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <p>
                    {{ field.label_tag }}<br>
                    {{ field }}<br>
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </p>
            {% endfor %}
            <p>
                <button type="submit">Zatwierdź</button>
            </p>
        </form>
{% endblock %}

forum/templates/forum/see_profile.html
{% extends 'forum/base.html' %}
{% load staticfiles %}

{% block title %}
    <link rel="stylesheet" href="{% static 'css/styles/index.css' %}">
    <style>
    .button {
      background-color: #f4511e;
      border: none;
      color: white;
      padding: 16px 32px;
      text-align: center;
      font-size: 16px;
      margin: 4px 2px;
      opacity: 0.6;
      transition: 0.3s;
      display: inline-block;
      text-decoration: none;
      cursor: pointer;
      float: right;
    }

    .button:hover {opacity: 1}

    td:hover {background-color: #DD4400}

    </style>
    <title>Profil {{ user.username }}</title>
{% endblock %}

{% block content %}
    <p></p>
    <table id="customers">
        <tr>
            <th>Nazwa użytkownika</th>
        </tr>
        <tr>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th>Email</th>
        </tr>
        <tr>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>Imie i nazwisko</th>
        </tr>
        <tr>
            <td>{{ user.first_name }}  {{ user.last_name }}</td>
        </tr>
    </table>
    <input class="button" value="Edytuj profil" onclick="window.location.href='{% url 'forum:profile_update' user.username %}'">
    <input class="button" value="Zmień hasło" onclick="window.location.href='{% url 'forum:password_change' user.username %}'">
    <input class="button" value="Usuń konto" onclick="window.location.href='{% url 'forum:user_delete' user.username %}'">
{% endblock %}

forum/templates/forum/signup.html
{% extends 'forum/base.html' %}

{% block title %}
    <style>
        body {
            background: antiquewhite url("../../static/css/ksiazka.jpg") no-repeat center;
            background-size: 1280px;
            background-position: 300px 80px;
        }

        .position {
            margin: auto;
            width: 50%;
            padding: 100px;
        }

        h2 {
            color: darkslategrey;
        }
    </style>
    <title>Rejestracja</title>
{% endblock %}

{% block content %}
    <div class="position">
        <h2>Rejestracja</h2>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <p>
                    {{ field.label_tag }}<br>
                    {{ field }}<br>
                    {% if field.help_text %}
                        <small style="color: darkblue">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </p>
            {% endfor %}
            <p>
                <button type="submit">Zarejestruj</button>
            </p>
        </form>
    </div>
{% endblock %}

forum/templates/forum/thread_details.html
{% extends 'forum/base.html' %}
{% load staticfiles %}

{% block title %}
    <link rel="stylesheet" href="{% static 'css/styles/thread_details.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ thread.title }}</title>
{% endblock %}

{% block content %}
    <h2>{{ thread.title }}</h2>

    <div class="row">
        <div class="column" style="width: 70%">
            <p class="border1">{{ thread.description}}</p>
        </div>
        <div class="column" style="width: 30%">
            <p>
                <h4>Autor:</h4>{{ thread.author }}
            </p>
            <p>
                <h4>Data opublikowania:</h4>{{ thread.creation_date }}<br>
            </p>
            {% if user.is_authenticated and user == thread.author %}
                <a href="{% url 'forum:thread_delete' thread.category_name thread.pk %}"><img src="../../static/css/X.jpg" height="20" width="20"></a>
            {% endif %}
            {#            PRZYCISK#}

        </div>
    </div>
    {% for post in thread.post_set.all %}
        <div class="row">
            <div class="column" style="width: 70%">
                <p class="border2">{{ post.text }}</p>
            </div>
            <div class="column" style="width: 30%">
            <br>
                <p>
                    <b>Autor: </b>{{ post.author }}
                </p>
                <p>
                    <b>Data odpowiedzi: </b>{{ post.posting_date }}
                </p>
{#                PRZYCISK#}
                {% if user.is_authenticated and user == post.author %}
                    <a href="{% url 'forum:delete_post' thread.category_name thread.pk post.pk %}"><img src="../../static/css/X.jpg" height="20" width="20"></a>
                {% endif %}
            </div>
        </div>
    {% endfor %}
    <p>
        {% if message %}
            <form method="post">
            {% csrf_token %}
                {% for field in form %}
                    <div class="wrapper">
                        <p>
                            {{ field }}<br>
                            {% for error in field.errors %}
                                <p style="color: red">{{ error }}</p>
                            {% endfor %}
                        </p>
                    </div>
                {% endfor %}
                <p>
                    <div class="wrapper">
                    <button class="button" type="submit">Zatwierdź</button>
                    </div>
                </p>
            </form>
        {% else %}
            <div class="wrapper">
                <input class="button" value="Odpowiedz" onclick="window.location.href='{% url 'forum:answer' category thread.pk %}'">
            </div>
        {% endif %}
    </p>
{% endblock %}

forum/templates/forum/threadlist.html
{% extends 'forum/base.html' %}
{% load staticfiles %}

{% block title %}
    <link rel="stylesheet" href="{% static 'css/styles/forum_view.css' %}">
    <title>{{ category }}</title>
{% endblock %}

{% block content %}
    <p></p>
    <table id="customers">
        <colgroup>
            <col width="330">
            <col width="70">
        </colgroup>
    {% for thread in threads %}
        <tr>
            <td style="background-color: #4CAF50">
                <a style="padding: 0.5em;" href="{% url 'forum:thread_details' thread.category_name thread.pk %}">{{ thread.title }}</a>
            </td>
            <td style="background-color: #4CAF50">
                {{ thread.author.username }}
            </td>
        </tr>
        <tr>
            <td rowspan="2" style="text-align: left">
                <a style="padding: 1.5em;" href="{% url 'forum:thread_details' thread.category_name thread.pk %}">{{ thread.description|truncatechars:60 }}</a>
            </td>
            <td>
                {{ thread.creation_date }}
            </td>
        </tr>
        <tr>
            <td>
                {{ thread.last_activity_date }}
            </td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}